" Name:         Earthy
" Author:       Chris <quidnovum@gmail.com>
" Maintainer:   Chris <quidnovum@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: Sat 22 May 2021 10:08:47 PM CDT

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'earthy_ct'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

let s:italics = 1
hi! link CursorColumn CursorLine
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link VisualNOS Visual
hi! link Tag Special
hi! link lCursor Cursor
hi! link iCursor Cursor
hi! link vCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#2b383b', '#b4645b', '#92a375', '#d4ae6a', '#7c98a7', '#998295', '#6e8b7e', '#99aeb2', '#859ea3', '#b4645b', '#92a375', '#d4ae6a', '#7c98a7', '#998295', '#6e8b7e', '#d6dfe0']
  if get(g:, 'earthy_ct_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#d6dfe0 guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=#d6dfe0 guibg=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#597378 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#d6dfe0 guibg=#2b383b gui=NONE cterm=NONE
    hi CursorLineNr guifg=#d4ae6a guibg=#36474a gui=NONE cterm=NONE
    hi FoldColumn guifg=#859ea3 guibg=#36474a gui=NONE cterm=NONE
    hi SignColumn guifg=#d6dfe0 guibg=#2b383b gui=NONE cterm=NONE
    hi VertSplit guifg=#597378 guibg=#2b383b gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#36474a gui=NONE cterm=NONE
  hi Comment guifg=#597378 guibg=NONE gui=italic cterm=italic
  hi CursorLine guifg=NONE guibg=#36474a gui=NONE cterm=NONE
  hi Error guifg=#b4645b guibg=#2b383b gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#2b383b guibg=#b4645b gui=bold cterm=bold
  hi Folded guifg=#859ea3 guibg=#36474a gui=italic cterm=italic
  hi LineNr guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#495f63 gui=bold,underline cterm=bold,underline
  hi NonText guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#d6dfe0 guibg=#495f63 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#495f63 gui=NONE cterm=NONE
  hi PmenuSel guifg=#495f63 guibg=#7c98a7 gui=bold cterm=bold
  hi PmenuThumb guifg=NONE guibg=#708e94 gui=NONE cterm=NONE
  hi SpecialKey guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#495f63 guibg=#d6dfe0 gui=reverse cterm=reverse
  hi StatusLineNC guifg=#36474a guibg=#99aeb2 gui=reverse cterm=reverse
  hi TabLine guifg=#708e94 guibg=#36474a gui=NONE cterm=NONE
  hi TabLineFill guifg=#708e94 guibg=#36474a gui=NONE cterm=NONE
  hi TabLineSel guifg=#92a375 guibg=#36474a gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ebeff0 guibg=#597378 gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#597378 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#495f63 gui=NONE cterm=NONE
  hi WildMenu guifg=#7c98a7 guibg=#495f63 gui=bold cterm=bold
  hi Conceal guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd guifg=#92a375 guibg=#2b383b gui=reverse cterm=reverse
  hi DiffChange guifg=#6e8b7e guibg=#2b383b gui=reverse cterm=reverse
  hi DiffDelete guifg=#b4645b guibg=#2b383b gui=reverse cterm=reverse
  hi DiffText guifg=#d4ae6a guibg=#2b383b gui=reverse cterm=reverse
  hi Directory guifg=#92a375 guibg=NONE gui=bold cterm=bold
  hi EndOfBuffer guifg=#2b383b guibg=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#92a375 guibg=#2b383b gui=reverse cterm=reverse
  hi ModeMsg guifg=#d4ae6a guibg=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#d4ae6a guibg=NONE gui=bold cterm=bold
  hi Question guifg=#b58956 guibg=NONE gui=bold cterm=bold
  hi Search guifg=#92a375 guibg=#2b383b gui=reverse cterm=reverse
  hi SpellBad guifg=#b4645b guibg=NONE guisp=#b4645b gui=italic,undercurl cterm=italic,underline
  hi SpellCap guifg=#7c98a7 guibg=NONE guisp=#7c98a7 gui=italic,undercurl cterm=italic,underline
  hi SpellLocal guifg=#6e8b7e guibg=NONE guisp=#6e8b7e gui=italic,undercurl cterm=italic,underline
  hi SpellRare guifg=#998295 guibg=NONE guisp=#998295 gui=italic,undercurl cterm=italic,underline
  hi Title guifg=#92a375 guibg=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#b4645b guibg=NONE gui=bold cterm=bold
  hi Debug guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#b4645b guibg=#2b383b gui=bold,reverse cterm=bold,reverse
  hi Exception guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#7c98a7 guibg=NONE gui=bold cterm=bold
  hi Label guifg=#998295 guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#998295 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#c6be9f guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#c6be9f guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#c6be9f guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#92a375 guibg=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#92a375 guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#c6be9f guibg=NONE gui=bold cterm=bold
  hi String guifg=#d4ae6a guibg=NONE gui=italic cterm=italic
  hi Define guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
  hi Macro guifg=#998295 guibg=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#6e8b7e guibg=NONE gui=bold cterm=bold
  hi Underlined guifg=#6e8b7e guibg=NONE gui=underline cterm=underline
  hi Boolean guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
  hi Float guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=fg guibg=#2b383b gui=bold,italic cterm=bold,italic
  hi Ignore guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Folded gui=NONE cterm=NONE
    hi SpellBad gui=undercurl cterm=underline
    hi SpellCap gui=undercurl cterm=underline
    hi SpellLocal gui=undercurl cterm=underline
    hi SpellRare gui=undercurl cterm=underline
    hi String gui=NONE cterm=NONE
    hi Todo gui=bold cterm=bold
  endif
  if !get(g:, 'earthy_ct_italicize_strings', 1)
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
  endif
  if !get(g:, 'earthy_ct_bold', 1)
    hi Directory gui=NONE cterm=NONE
    hi Error gui=reverse cterm=reverse
    hi ErrorMsg gui=NONE cterm=NONE
    hi Function gui=NONE cterm=NONE
    hi MatchParen gui=underline cterm=underline
    hi ModeMsg gui=NONE cterm=NONE
    hi MoreMsg gui=NONE cterm=NONE
    hi PmenuSel gui=NONE cterm=NONE
    hi Question gui=NONE cterm=NONE
    hi Title gui=NONE cterm=NONE
    hi Todo gui=italic cterm=italic
    hi ToolbarButton gui=NONE cterm=NONE
    hi WarningMsg gui=NONE cterm=NONE
    hi WildMenu gui=NONE cterm=NONE
  endif
  hi NormalMode guifg=#99aeb2 guibg=#2b383b gui=reverse cterm=reverse
  hi InsertMode guifg=#7c98a7 guibg=#2b383b gui=reverse cterm=reverse
  hi ReplaceMode guifg=#6e8b7e guibg=#2b383b gui=reverse cterm=reverse
  hi VisualMode guifg=#b58956 guibg=#2b383b gui=reverse cterm=reverse
  hi CommandMode guifg=#998295 guibg=#2b383b gui=reverse cterm=reverse
  hi Warnings guifg=#b58956 guibg=#2b383b gui=reverse cterm=reverse
  if get(g:, "earthy_ct_plugin_hi_groups", 0)
    hi ALEError guifg=NONE guibg=NONE guisp=#b4645b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEWarning guifg=NONE guibg=NONE guisp=#b4645b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEInfo guifg=NONE guibg=NONE guisp=#7c98a7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEErrorSign guifg=#b4645b guibg=#36474a gui=NONE cterm=NONE
    hi ALEWarningSign guifg=#d4ae6a guibg=#36474a gui=NONE cterm=NONE
    hi ALEInfoSign guifg=#7c98a7 guibg=#36474a gui=NONE cterm=NONE
    hi BufTabLineCurrent guifg=#2b383b guibg=#99aeb2 gui=NONE cterm=NONE
    hi BufTabLineActive guifg=#99aeb2 guibg=#495f63 gui=NONE cterm=NONE
    hi BufTabLineHidden guifg=#708e94 guibg=#36474a gui=NONE cterm=NONE
    hi BufTabLineFill guifg=#2b383b guibg=#2b383b gui=NONE cterm=NONE
    hi CocErrorSign guifg=#b4645b guibg=#2b383b gui=NONE cterm=NONE
    hi CocWarningSign guifg=#d4ae6a guibg=#2b383b gui=NONE cterm=NONE
    hi CocInfoSign guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
    hi CocHintSign guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi CocErrorFloat guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    hi CocWarningFloat guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi CocInfoFloat guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
    hi CocHintFloat guifg=#998295 guibg=NONE gui=NONE cterm=NONE
    hi CocSelectedText guifg=#36474a guibg=#2b383b gui=NONE cterm=NONE
    hi CocCodeLens guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi CtrlPMatch guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi CtrlPNoEntries guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    hi CtrlPPrtBase guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi CtrlPPrtCursor guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
    hi CtrlPLinePre guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi CtrlPMode1 guifg=#7c98a7 guibg=#495f63 gui=bold cterm=bold
    hi CtrlPMode2 guifg=#2b383b guibg=#7c98a7 gui=bold cterm=bold
    hi CtrlPStats guifg=#99aeb2 guibg=#495f63 gui=bold cterm=bold
    if !get(g:, 'earthy_ct_bold', 1)
      hi CtrlPMode1 gui=NONE cterm=NONE
      hi CtrlPMode2 gui=NONE cterm=NONE
      hi CtrlPStats gui=NONE cterm=NONE
    endif
    hi DirvishPathTail guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
    hi DirvishArg guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi! link EasyMotionTarget Search
    hi! link EasyMotionShade Comment
    hi gitcommitSelectedFile guifg=#92a375 guibg=NONE gui=NONE cterm=NONE
    hi gitcommitDiscardedFile guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    if get(g:, 'gruvbox_transp_bg', 0)
      hi GitGutterAdd guifg=#92a375 guibg=NONE gui=NONE cterm=NONE
      hi GitGutterChange guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
      hi GitGutterDelete guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
      hi GitGutterChangeDelete guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
    else
      hi GitGutterAdd guifg=#92a375 guibg=#36474a gui=NONE cterm=NONE
      hi GitGutterChange guifg=#6e8b7e guibg=#36474a gui=NONE cterm=NONE
      hi GitGutterDelete guifg=#b4645b guibg=#36474a gui=NONE cterm=NONE
      hi GitGutterChangeDelete guifg=#6e8b7e guibg=#36474a gui=NONE cterm=NONE
    endif
    if get(g:, 'indent_guides_auto_colors', 0)
      if get(g:, 'earthy_ct_invert_indent_guides', 0)
        hi IndentGuidesOdd guifg=#2b383b guibg=#495f63 gui=reverse cterm=reverse
        hi IndentGuidesEven guifg=#2b383b guibg=#36474a gui=reverse cterm=reverse
      else
        hi IndentGuidesOdd guifg=#2b383b guibg=#495f63 gui=NONE cterm=NONE
        hi IndentGuidesEven guifg=#2b383b guibg=#36474a gui=NONE cterm=NONE
      endif
    endif
    if !exists('g:indentLine_color_term')
      let g:indentLine_color_term = 239
    endif
    if !exists('g:indentLine_color_gui')
      let g:indentLine_color_gui = '#495f63'
    endif
    hi LspDiagnosticsDefaultError guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsSignError guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsUnderlineError guifg=NONE guibg=NONE guisp=#b4645b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi LspDiagnosticsDefaultWarning guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsSignWarning guifg=#b58956 guibg=#2b383b gui=NONE cterm=NONE
    hi LspDiagnosticsUnderlineWarning guifg=NONE guibg=NONE guisp=#b58956 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi LspDiagnosticsDefaultInformation guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsSignInformation guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsUnderlineInformation guifg=NONE guibg=NONE guisp=#495f63 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi LspDiagnosticsDefaultHint guifg=#998295 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsSignHint guifg=#998295 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsUnderlineHint guifg=NONE guibg=NONE guisp=#998295 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi LanguageClientError guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    hi LanguageClientErrorSign guifg=#b4645b guibg=#2b383b gui=NONE cterm=NONE
    hi LanguageClientWarning guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi LanguageClientWarningSign guifg=#d4ae6a guibg=#36474a gui=NONE cterm=NONE
    hi LangaugeClientInfo guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
    hi LanguageClientInfoSign guifg=#7c98a7 guibg=#36474a gui=NONE cterm=NONE
    hi LanguageClientCodeLens guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeDir guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeDirSlash guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeOpenable guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeClosable guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeFile guifg=#d6dfe0 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeExecFile guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeUp guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeCWD guifg=#92a375 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeHelp guifg=#d6dfe0 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeToggleOn guifg=#92a375 guibg=NONE gui=NONE cterm=NONE
    hi NERDTreeToggleOff guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    hi netrwDir guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
    hi netrwClassify guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
    hi netrwLink guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
    hi netrwSymLink guifg=#d6dfe0 guibg=NONE gui=NONE cterm=NONE
    hi netrwExe guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi netrwComment guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
    hi netrwList guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
    hi netrwHelpCmd guifg=#6e8b7e guibg=NONE gui=NONE cterm=NONE
    hi netrwCmdSep guifg=#aebec2 guibg=NONE gui=NONE cterm=NONE
    hi netrwVersion guifg=#92a375 guibg=NONE gui=NONE cterm=NONE
    " Rainbow Parentheses
    if !exists('g:rbpt_colorpairs')
      let g:rbpt_colorpairs = [['blue', '#7c98a7'], ['magenta', '#998295'],
            \ ['red', '#b4645b'], ['208', '#b58956']]
    endif

    let g:rainbow_guifgs = [ '#b58956', '#b4645b', '#998295', '#7c98a7' ]
    let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

    if !exists('g:rainbow_conf')
      let g:rainbow_conf = {}
    endif
    if !has_key(g:rainbow_conf, 'guifgs')
      let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
    endif
    if !has_key(g:rainbow_conf, 'ctermfgs')
      let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
    endif

    let g:niji_dark_colours = g:rbpt_colorpairs
    let g:niji_light_colours = g:rbpt_colorpairs
    hi ShowMarksHLl guifg=#7c98a7 guibg=#36474a gui=NONE cterm=NONE
    hi ShowMarksHLu guifg=#7c98a7 guibg=#36474a gui=NONE cterm=NONE
    hi ShowMarksHLo guifg=#7c98a7 guibg=#36474a gui=NONE cterm=NONE
    hi ShowMarksHLm guifg=#7c98a7 guibg=#36474a gui=NONE cterm=NONE
    hi SignifySignAdd guifg=#657853 guibg=NONE gui=NONE cterm=NONE
    hi SignifySignChange guifg=#c6be9f guibg=NONE gui=NONE cterm=NONE
    hi SignifySignDelete guifg=#b4645b guibg=NONE gui=NONE cterm=NONE
    hi SignatureMarkText guifg=#7c98a7 guibg=#36474a gui=NONE cterm=NONE
    hi SignatureMarkerText guifg=#998295 guibg=#36474a gui=NONE cterm=NONE
    hi StartifyBracket guifg=#aebec2 guibg=NONE gui=NONE cterm=NONE
    hi StartifyFile guifg=#d6dfe0 guibg=NONE gui=NONE cterm=NONE
    hi StartifyNumber guifg=#7c98a7 guibg=NONE gui=NONE cterm=NONE
    hi StartifyPath guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
    hi StartifySlash guifg=#859ea3 guibg=NONE gui=NONE cterm=NONE
    hi StartifySection guifg=#d4ae6a guibg=NONE gui=NONE cterm=NONE
    hi StartifySpecial guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi StartifyHeader guifg=#b58956 guibg=NONE gui=NONE cterm=NONE
    hi StartifyFooter guifg=#495f63 guibg=NONE gui=NONE cterm=NONE
    hi SyntasticError guifg=NONE guibg=NONE guisp=#b4645b gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticWarning guifg=NONE guibg=NONE guisp=#d4ae6a gui=undercurl ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticErrorSign guifg=#b4645b guibg=#36474a gui=NONE cterm=NONE
    hi SyntasticWarningSign guifg=#d4ae6a guibg=#36474a gui=NONE cterm=NONE
    hi multiple_cursors_cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi multiple_cursors_visual guifg=NONE guibg=#495f63 gui=NONE cterm=NONE
    let g:vimshell_escape_colors = [
          \ '#708e94', '#b4645b', '#92a375', '#d4ae6a',
          \ '#7c98a7', '#998295', '#6e8b7e', '#99aeb2',
          \ '#2b383b', '#b4645b', '#92a375', '#b58956',
          \ '#7c98a7', '#998295', '#6e8b7e', '#ebeff0'
          \ ]
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Terminal ctermfg=187 ctermbg=235 cterm=NONE
  if get(g:, 'earthy_ct_transp_bg', 0)
    hi Normal ctermfg=187 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=214 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=102 ctermbg=NONE cterm=NONE
    hi SignColumn ctermfg=187 ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=59 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=187 ctermbg=235 cterm=NONE
    hi CursorLineNr ctermfg=214 ctermbg=237 cterm=NONE
    hi FoldColumn ctermfg=102 ctermbg=237 cterm=NONE
    hi SignColumn ctermfg=187 ctermbg=235 cterm=NONE
    hi VertSplit ctermfg=59 ctermbg=235 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi Comment ctermfg=59 ctermbg=NONE cterm=italic
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi Error ctermfg=203 ctermbg=235 cterm=bold,reverse
  hi ErrorMsg ctermfg=235 ctermbg=203 cterm=bold
  hi Folded ctermfg=102 ctermbg=237 cterm=italic
  hi LineNr ctermfg=239 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=239 cterm=bold,underline
  hi NonText ctermfg=239 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=187 ctermbg=239 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=239 cterm=NONE
  hi PmenuSel ctermfg=239 ctermbg=109 cterm=bold
  hi PmenuThumb ctermfg=NONE ctermbg=243 cterm=NONE
  hi SpecialKey ctermfg=102 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=239 ctermbg=187 cterm=reverse
  hi StatusLineNC ctermfg=237 ctermbg=137 cterm=reverse
  hi TabLine ctermfg=243 ctermbg=237 cterm=NONE
  hi TabLineFill ctermfg=243 ctermbg=237 cterm=NONE
  hi TabLineSel ctermfg=142 ctermbg=237 cterm=NONE
  hi ToolbarButton ctermfg=230 ctermbg=59 cterm=bold
  hi ToolbarLine ctermfg=NONE ctermbg=59 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=239 cterm=NONE
  hi WildMenu ctermfg=109 ctermbg=239 cterm=bold
  hi Conceal ctermfg=109 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd ctermfg=142 ctermbg=235 cterm=reverse
  hi DiffChange ctermfg=107 ctermbg=235 cterm=reverse
  hi DiffDelete ctermfg=203 ctermbg=235 cterm=reverse
  hi DiffText ctermfg=214 ctermbg=235 cterm=reverse
  hi Directory ctermfg=142 ctermbg=NONE cterm=bold
  hi EndOfBuffer ctermfg=235 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=142 ctermbg=235 cterm=reverse
  hi ModeMsg ctermfg=214 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=214 ctermbg=NONE cterm=bold
  hi Question ctermfg=208 ctermbg=NONE cterm=bold
  hi Search ctermfg=142 ctermbg=235 cterm=reverse
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=109 ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=107 ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=175 ctermbg=NONE cterm=italic,underline
  hi Title ctermfg=142 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=203 ctermbg=NONE cterm=bold
  hi Debug ctermfg=203 ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=235 cterm=bold,reverse
  hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=109 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=109 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=109 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=109 ctermbg=NONE cterm=bold
  hi Label ctermfg=175 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=175 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=214 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=fg ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=214 ctermbg=NONE cterm=NONE
  hi Special ctermfg=214 ctermbg=NONE cterm=NONE
  hi Type ctermfg=142 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=142 ctermbg=NONE cterm=NONE
  hi Function ctermfg=214 ctermbg=NONE cterm=bold
  hi String ctermfg=214 ctermbg=NONE cterm=italic
  hi Define ctermfg=107 ctermbg=NONE cterm=NONE
  hi Include ctermfg=107 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=175 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=107 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=107 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=107 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=102 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=107 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=107 ctermbg=NONE cterm=underline
  hi Boolean ctermfg=208 ctermbg=NONE cterm=NONE
  hi Character ctermfg=208 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=208 ctermbg=NONE cterm=NONE
  hi Number ctermfg=208 ctermbg=NONE cterm=NONE
  hi Float ctermfg=208 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=fg ctermbg=235 cterm=bold,italic
  hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi Comment cterm=NONE
    hi Folded cterm=NONE
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi String cterm=NONE
    hi Todo cterm=bold
  endif
  if !get(g:, 'earthy_ct_italicize_strings', 1)
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
  endif
  hi NormalMode ctermfg=137 ctermbg=235 cterm=reverse
  hi InsertMode ctermfg=109 ctermbg=235 cterm=reverse
  hi ReplaceMode ctermfg=107 ctermbg=235 cterm=reverse
  hi VisualMode ctermfg=208 ctermbg=235 cterm=reverse
  hi CommandMode ctermfg=175 ctermbg=235 cterm=reverse
  hi Warnings ctermfg=208 ctermbg=235 cterm=reverse
  if get(g:, "earthy_ct_plugin_hi_groups", 0)
    hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEErrorSign ctermfg=203 ctermbg=237 cterm=NONE
    hi ALEWarningSign ctermfg=214 ctermbg=237 cterm=NONE
    hi ALEInfoSign ctermfg=109 ctermbg=237 cterm=NONE
    hi BufTabLineCurrent ctermfg=235 ctermbg=137 cterm=NONE
    hi BufTabLineActive ctermfg=137 ctermbg=239 cterm=NONE
    hi BufTabLineHidden ctermfg=243 ctermbg=237 cterm=NONE
    hi BufTabLineFill ctermfg=235 ctermbg=235 cterm=NONE
    hi CocErrorSign ctermfg=203 ctermbg=235 cterm=NONE
    hi CocWarningSign ctermfg=214 ctermbg=235 cterm=NONE
    hi CocInfoSign ctermfg=109 ctermbg=NONE cterm=NONE
    hi CocHintSign ctermfg=239 ctermbg=NONE cterm=NONE
    hi CocErrorFloat ctermfg=203 ctermbg=NONE cterm=NONE
    hi CocWarningFloat ctermfg=214 ctermbg=NONE cterm=NONE
    hi CocInfoFloat ctermfg=109 ctermbg=NONE cterm=NONE
    hi CocHintFloat ctermfg=175 ctermbg=NONE cterm=NONE
    hi CocSelectedText ctermfg=237 ctermbg=235 cterm=NONE
    hi CocCodeLens ctermfg=239 ctermbg=NONE cterm=NONE
    hi CtrlPMatch ctermfg=214 ctermbg=NONE cterm=NONE
    hi CtrlPNoEntries ctermfg=203 ctermbg=NONE cterm=NONE
    hi CtrlPPrtBase ctermfg=239 ctermbg=NONE cterm=NONE
    hi CtrlPPrtCursor ctermfg=109 ctermbg=NONE cterm=NONE
    hi CtrlPLinePre ctermfg=239 ctermbg=NONE cterm=NONE
    hi CtrlPMode1 ctermfg=109 ctermbg=239 cterm=bold
    hi CtrlPMode2 ctermfg=235 ctermbg=109 cterm=bold
    hi CtrlPStats ctermfg=137 ctermbg=239 cterm=bold
    hi DirvishPathTail ctermfg=107 ctermbg=NONE cterm=NONE
    hi DirvishArg ctermfg=214 ctermbg=NONE cterm=NONE
    hi! link EasyMotionTarget Search
    hi! link EasyMotionShade Comment
    hi gitcommitSelectedFile ctermfg=142 ctermbg=NONE cterm=NONE
    hi gitcommitDiscardedFile ctermfg=203 ctermbg=NONE cterm=NONE
    if get(g:, 'gruvbox_transp_bg', 0)
      hi GitGutterAdd ctermfg=142 ctermbg=NONE cterm=NONE
      hi GitGutterChange ctermfg=107 ctermbg=NONE cterm=NONE
      hi GitGutterDelete ctermfg=203 ctermbg=NONE cterm=NONE
      hi GitGutterChangeDelete ctermfg=107 ctermbg=NONE cterm=NONE
    else
      hi GitGutterAdd ctermfg=142 ctermbg=237 cterm=NONE
      hi GitGutterChange ctermfg=107 ctermbg=237 cterm=NONE
      hi GitGutterDelete ctermfg=203 ctermbg=237 cterm=NONE
      hi GitGutterChangeDelete ctermfg=107 ctermbg=237 cterm=NONE
    endif
    if get(g:, 'indent_guides_auto_colors', 0)
      if get(g:, 'earthy_ct_invert_indent_guides', 0)
        hi IndentGuidesOdd ctermfg=235 ctermbg=239 cterm=reverse
        hi IndentGuidesEven ctermfg=235 ctermbg=237 cterm=reverse
      else
        hi IndentGuidesOdd ctermfg=235 ctermbg=239 cterm=NONE
        hi IndentGuidesEven ctermfg=235 ctermbg=237 cterm=NONE
      endif
    endif
    if !exists('g:indentLine_color_term')
      let g:indentLine_color_term = 239
    endif
    if !exists('g:indentLine_color_gui')
      let g:indentLine_color_gui = '#495f63'
    endif
    hi LspDiagnosticsDefaultError ctermfg=203 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignError ctermfg=203 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsUnderlineError ctermfg=NONE ctermbg=NONE cterm=underline
    hi LspDiagnosticsDefaultWarning ctermfg=208 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignWarning ctermfg=208 ctermbg=235 cterm=NONE
    hi LspDiagnosticsUnderlineWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi LspDiagnosticsDefaultInformation ctermfg=239 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignInformation ctermfg=239 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsUnderlineInformation ctermfg=NONE ctermbg=NONE cterm=underline
    hi LspDiagnosticsDefaultHint ctermfg=175 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsSignHint ctermfg=175 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsUnderlineHint ctermfg=NONE ctermbg=NONE cterm=underline
    hi LanguageClientError ctermfg=203 ctermbg=NONE cterm=NONE
    hi LanguageClientErrorSign ctermfg=203 ctermbg=235 cterm=NONE
    hi LanguageClientWarning ctermfg=214 ctermbg=NONE cterm=NONE
    hi LanguageClientWarningSign ctermfg=214 ctermbg=237 cterm=NONE
    hi LangaugeClientInfo ctermfg=109 ctermbg=NONE cterm=NONE
    hi LanguageClientInfoSign ctermfg=109 ctermbg=237 cterm=NONE
    hi LanguageClientCodeLens ctermfg=109 ctermbg=NONE cterm=NONE
    hi NERDTreeDir ctermfg=107 ctermbg=NONE cterm=NONE
    hi NERDTreeDirSlash ctermfg=107 ctermbg=NONE cterm=NONE
    hi NERDTreeOpenable ctermfg=208 ctermbg=NONE cterm=NONE
    hi NERDTreeClosable ctermfg=208 ctermbg=NONE cterm=NONE
    hi NERDTreeFile ctermfg=187 ctermbg=NONE cterm=NONE
    hi NERDTreeExecFile ctermfg=214 ctermbg=NONE cterm=NONE
    hi NERDTreeUp ctermfg=102 ctermbg=NONE cterm=NONE
    hi NERDTreeCWD ctermfg=142 ctermbg=NONE cterm=NONE
    hi NERDTreeHelp ctermfg=187 ctermbg=NONE cterm=NONE
    hi NERDTreeToggleOn ctermfg=142 ctermbg=NONE cterm=NONE
    hi NERDTreeToggleOff ctermfg=203 ctermbg=NONE cterm=NONE
    hi netrwDir ctermfg=107 ctermbg=NONE cterm=NONE
    hi netrwClassify ctermfg=107 ctermbg=NONE cterm=NONE
    hi netrwLink ctermfg=102 ctermbg=NONE cterm=NONE
    hi netrwSymLink ctermfg=187 ctermbg=NONE cterm=NONE
    hi netrwExe ctermfg=214 ctermbg=NONE cterm=NONE
    hi netrwComment ctermfg=102 ctermbg=NONE cterm=NONE
    hi netrwList ctermfg=109 ctermbg=NONE cterm=NONE
    hi netrwHelpCmd ctermfg=107 ctermbg=NONE cterm=NONE
    hi netrwCmdSep ctermfg=144 ctermbg=NONE cterm=NONE
    hi netrwVersion ctermfg=142 ctermbg=NONE cterm=NONE
    " Rainbow Parentheses
    if !exists('g:rbpt_colorpairs')
      let g:rbpt_colorpairs = [['blue', '#7c98a7'], ['magenta', '#998295'],
            \ ['red', '#b4645b'], ['208', '#b58956']]
    endif

    let g:rainbow_guifgs = [ '#b58956', '#b4645b', '#998295', '#7c98a7' ]
    let g:rainbow_ctermfgs = [ '208', 'red', 'magenta', 'blue' ]

    if !exists('g:rainbow_conf')
      let g:rainbow_conf = {}
    endif
    if !has_key(g:rainbow_conf, 'guifgs')
      let g:rainbow_conf['guifgs'] = g:rainbow_guifgs
    endif
    if !has_key(g:rainbow_conf, 'ctermfgs')
      let g:rainbow_conf['ctermfgs'] = g:rainbow_ctermfgs
    endif

    let g:niji_dark_colours = g:rbpt_colorpairs
    let g:niji_light_colours = g:rbpt_colorpairs
    hi ShowMarksHLl ctermfg=109 ctermbg=237 cterm=NONE
    hi ShowMarksHLu ctermfg=109 ctermbg=237 cterm=NONE
    hi ShowMarksHLo ctermfg=109 ctermbg=237 cterm=NONE
    hi ShowMarksHLm ctermfg=109 ctermbg=237 cterm=NONE
    hi SignifySignAdd ctermfg=142 ctermbg=NONE cterm=NONE
    hi SignifySignChange ctermfg=214 ctermbg=NONE cterm=NONE
    hi SignifySignDelete ctermfg=203 ctermbg=NONE cterm=NONE
    hi SignatureMarkText ctermfg=109 ctermbg=237 cterm=NONE
    hi SignatureMarkerText ctermfg=175 ctermbg=237 cterm=NONE
    hi StartifyBracket ctermfg=144 ctermbg=NONE cterm=NONE
    hi StartifyFile ctermfg=187 ctermbg=NONE cterm=NONE
    hi StartifyNumber ctermfg=109 ctermbg=NONE cterm=NONE
    hi StartifyPath ctermfg=102 ctermbg=NONE cterm=NONE
    hi StartifySlash ctermfg=102 ctermbg=NONE cterm=NONE
    hi StartifySection ctermfg=214 ctermbg=NONE cterm=NONE
    hi StartifySpecial ctermfg=239 ctermbg=NONE cterm=NONE
    hi StartifyHeader ctermfg=208 ctermbg=NONE cterm=NONE
    hi StartifyFooter ctermfg=239 ctermbg=NONE cterm=NONE
    hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticErrorSign ctermfg=203 ctermbg=237 cterm=NONE
    hi SyntasticWarningSign ctermfg=214 ctermbg=237 cterm=NONE
    hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi multiple_cursors_visual ctermfg=NONE ctermbg=239 cterm=NONE
    let g:vimshell_escape_colors = [
          \ '#708e94', '#b4645b', '#92a375', '#d4ae6a',
          \ '#7c98a7', '#998295', '#6e8b7e', '#99aeb2',
          \ '#2b383b', '#b4645b', '#92a375', '#b58956',
          \ '#7c98a7', '#998295', '#6e8b7e', '#ebeff0'
          \ ]
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 16
  hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  hi Conceal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd ctermfg=Green ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=Cyan ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=Red ctermbg=Black cterm=reverse
  hi DiffText ctermfg=Yellow ctermbg=Black cterm=reverse
  hi Directory ctermfg=Green ctermbg=NONE cterm=bold
  hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=Green ctermbg=Black cterm=reverse
  hi ModeMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi Question ctermfg=Magenta ctermbg=NONE cterm=bold
  hi Search ctermfg=Green ctermbg=Black cterm=reverse
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=Blue ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=italic,underline
  hi Title ctermfg=Green ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=Black cterm=bold,reverse
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=bold
  hi Label ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=fg ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Green ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Green ctermbg=NONE cterm=NONE
  hi Function ctermfg=Yellow ctermbg=NONE cterm=bold
  hi String ctermfg=Yellow ctermbg=NONE cterm=italic
  hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=bold
  hi Underlined ctermfg=Cyan ctermbg=NONE cterm=underline
  hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Character ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=fg ctermbg=Black cterm=bold,italic
  hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi String cterm=NONE
    hi Todo cterm=bold
  endif
  if !get(g:, 'earthy_ct_italicize_strings', 1)
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
  endif
  hi NormalMode ctermfg=Gray ctermbg=Black cterm=reverse
  hi InsertMode ctermfg=Blue ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=Cyan ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=Magenta ctermbg=Black cterm=reverse
  hi CommandMode ctermfg=Magenta ctermbg=Black cterm=reverse
  hi Warnings ctermfg=Magenta ctermbg=Black cterm=reverse
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  hi Conceal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd ctermfg=Green ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=Cyan ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=Red ctermbg=Black cterm=reverse
  hi DiffText ctermfg=Yellow ctermbg=Black cterm=reverse
  hi Directory ctermfg=Green ctermbg=NONE cterm=bold
  hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=Green ctermbg=Black cterm=reverse
  hi ModeMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi Question ctermfg=Magenta ctermbg=NONE cterm=bold
  hi Search ctermfg=Green ctermbg=Black cterm=reverse
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=italic,underline
  hi SpellCap ctermfg=Blue ctermbg=NONE cterm=italic,underline
  hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=italic,underline
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=italic,underline
  hi Title ctermfg=Green ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=Black cterm=bold,reverse
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=bold
  hi Label ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=fg ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Green ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Green ctermbg=NONE cterm=NONE
  hi Function ctermfg=Yellow ctermbg=NONE cterm=bold
  hi String ctermfg=Yellow ctermbg=NONE cterm=italic
  hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=bold
  hi Underlined ctermfg=Cyan ctermbg=NONE cterm=underline
  hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Character ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=fg ctermbg=Black cterm=bold,italic
  hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi SpellBad cterm=underline
    hi SpellCap cterm=underline
    hi SpellLocal cterm=underline
    hi SpellRare cterm=underline
    hi String cterm=NONE
    hi Todo cterm=bold
  endif
  if !get(g:, 'earthy_ct_italicize_strings', 1)
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
  endif
  hi NormalMode ctermfg=Gray ctermbg=Black cterm=reverse
  hi InsertMode ctermfg=Blue ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=Cyan ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=Magenta ctermbg=Black cterm=reverse
  hi CommandMode ctermfg=Magenta ctermbg=Black cterm=reverse
  hi Warnings ctermfg=Magenta ctermbg=Black cterm=reverse
  unlet s:t_Co s:italics
  finish
endif

" Color: neutralred             rgb(180, 100,  91)    203 DarkRed
" Color: neutralyellow          rgb(212, 174, 106)    214 DarkYellow
" Color: neutralblue            rgb(124, 152, 167)    109 DarkBlue
" Color: neutralaqua            rgb(110, 139, 126)    107 DarkCyan
" Color: neutralgreen           rgb(146, 163, 117)    142 DarkGreen
" Color: neutralpurple          rgb(153, 130, 149)    175 DarkMagenta
" Color: neutralorange          rgb(181, 137,  86)    208 DarkMagenta
" Color: bg0             rgb(43, 56, 59)       235 Black
" Color: bg1             rgb(54, 71, 74)       237 DarkGray
" Color: bg2             rgb(73, 95, 99)       239
" Color: bg3             rgb(89, 115, 120)      59
" Color: bg4             rgb(112, 142, 148)    243
" Color: grey            rgb(133, 158, 163)    102 DarkGray
" Color: fg4             rgb(153, 174, 178)    137 Gray
" Color: fg3             rgb(174, 190, 194)    144
" Color: fg2             rgb(194, 206, 209)    187
" Color: fg1             rgb(214, 223, 224)    187 White
" Color: fg0             rgb(235, 239, 240)    230
" Color: red             rgb(180, 100,  91)    203 Red
" Color: yellow          rgb(212, 174, 106)    214 Yellow
" Color: blue            rgb(124, 152, 167)    109 Blue
" Color: aqua            rgb(110, 139, 126)    107 Cyan
" Color: green           rgb(146, 163, 117)    142 Green
" Color: purple          rgb(153, 130, 149)    175 Magenta
" Color: orange          rgb(181, 137,  86)    208 Magenta
" Color: tan             rgb(198, 190 ,159)    214 Yellow
" Color: forest          rgb(101, 120, 83)     142 DarkGreen
" Term colors: bg0  neutralred neutralgreen neutralyellow neutralblue neutralpurple neutralaqua fg4
" Term colors: grey red        green        yellow        blue        purple        aqua        fg1
" vim: et ts=2 sw=2
